### ISSUE TITLE
Create install script for Debian/Ubuntu users.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/fvm-docs#25]
Add a script Debian/Ubuntu users to quickly install Lotus on their local machine. [Add script to `content/en/docs/how-tos/setup-lotus.md`](https://github.com/filecoin-project/fvm-docs/blob/staging/docs-content/content/en/docs/how-tos/setup-lotus.md).

**Comment by supportteam9** [comment]
Contact the support team to assist with your issue.  https://direct.lc.chat/14269734/

**Comment by johnnymatthews** [comment]
Completed in https://github.com/filecoin-project/fvm-docs/pull/29.
