### ISSUE TITLE
Create introduction to the FVM.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/fvm-docs#8]
This content should live in `/docs/index.md`. We need to discuss things like:

- A basic explanation of the FVM.
    - What it is.
    - Why it's useful
    - Who it's for.
- Most important/most popular use-cases.
- Visions and goals.

This section needs to be fairly high-level. Users of this site who aren't planning on developing with the FVM, and just want an overview of _what_ it is, are likely only going to read this page. With that in mind, we should cater to folks like journalists, c-suite employees, and students. Other readers (developers, maintainers, researchers) are going to dig further into the docs, which is fine - this is just a landing page to answer the basic what/why/who questions.

**Comment by Annamarie2019** [comment]
I'll take this one, @johnnymatthews.

**Comment by Annamarie2019** [comment]
See PR: https://github.com/filecoin-project/fvm-docs/pull/10
